"""
k_predictor.py — Ace: MLB pitcher strikeout prop prediction.

Sibling to agents/predictor.py's Homer (HR model). Same philosophy: gather
real signals, score deterministically, blend in a LightGBM model once one
exists. No LLM involved in ranking.

Reuses Homer's EV/Kelly math and the (Task 1-extended) pitcher recent-form
fetch. Owns its own Statcast fetch, its own odds market (pitcher_strikeouts,
not batter_home_runs), its own DB table (pick_factors_k), and its own site
page — a bug here cannot affect the HR pipeline.
"""
import csv
import io
from datetime import date
from pathlib import Path

import requests

from agents.predictor import (
    SAVANT_BASE, MLB_API_BASE, ODDS_API_BASE, _HEADERS,
    _compute_ev, _compute_kelly, _american_to_implied_prob,
    _fetch_pitcher_recent_form,
)


def _fetch_pitcher_k_statcast() -> dict:
    """
    Fetch the full Statcast pitcher K-rate leaderboard CSV, keyed by
    player_id (primary) and lowercased name (secondary). Columns:
    k_percent, whiff_percent, csw_percent, swinging_strike_percent.
    Caches to cache/statcast_pitcher_k_YYYY-MM-DD.csv (one fetch per day).
    """
    season    = date.today().year
    today_str = date.today().isoformat()
    cache_path = Path(__file__).parent.parent / "cache" / f"statcast_pitcher_k_{today_str}.csv"

    if cache_path.exists():
        text = cache_path.read_text(encoding="utf-8")
    else:
        url = (
            f"{SAVANT_BASE}/leaderboard/custom"
            f"?year={season}&type=pitcher&filter=&sort=4&sortDir=desc&min=5"
            f"&selections=k_percent,whiff_percent,csw_percent,swinging_strike_percent"
            f"&chart=false&r=no&exactNameSearch=false&csv=true"
        )
        try:
            resp = requests.get(url, headers=_HEADERS, timeout=20)
            resp.raise_for_status()
            text = resp.text.lstrip('﻿')
            cache_path.parent.mkdir(exist_ok=True)
            cache_path.write_text(text, encoding="utf-8")
        except Exception:
            return {}

    try:
        reader = csv.DictReader(io.StringIO(text))
        result = {}
        for row in reader:
            name = (row.get("last_name, first_name") or row.get("player_name") or "").lower()
            pid_raw = row.get("player_id") or row.get("pitcher") or ""
            try:
                result[int(pid_raw)] = row
            except (ValueError, TypeError):
                pass
            if name:
                result.setdefault(name, row)
        return result
    except Exception:
        return {}


# Pitch type code → bucket, same taxonomy as predictor.py's _PITCH_BUCKETS.
_PITCH_BUCKETS_K = {
    "FF": "fastball", "SI": "fastball", "FC": "fastball",
    "SL": "breaking", "CU": "breaking", "KC": "breaking", "ST": "breaking",
    "SV": "breaking", "CS": "breaking",
    "CH": "offspeed", "FS": "offspeed", "SC": "offspeed",
    "FO": "offspeed", "KN": "offspeed",
}


def _fetch_pitch_arsenal_whiff(player_ids: list[int], player_type: str) -> dict[int, dict]:
    """
    Fetch whiff% by pitch-type bucket (fastball/breaking/offspeed) from
    Savant's pitch-arsenal-stats leaderboard, PA-weighted per bucket.

    player_type="pitcher": each pitcher's own whiff% generated by the pitch
    types he throws (a "does he have a wipeout pitch" signal).
    player_type="batter": each batter's whiff% against each pitch-type
    bucket (used to build the opposing-lineup matchup signal).

    Returns {player_id: {"whiff_fastball": float|None, "whiff_breaking": ...,
    "whiff_offspeed": ...}}. Early season: sparse buckets return None for
    that key rather than being omitted from the dict.
    """
    if not player_ids:
        return {}
    year = date.today().year
    try:
        resp = requests.get(
            f"{SAVANT_BASE}/leaderboard/pitch-arsenal-stats"
            f"?type={player_type}&year={year}&team=&min=1&csv=true",
            timeout=30,
            headers=_HEADERS,
        )
        resp.raise_for_status()
        text = resp.text.lstrip('﻿')
        rows = list(csv.DictReader(io.StringIO(text)))
    except Exception:
        return {}

    def _sf(val):
        if val in (None, "", "null"):
            return None
        try:
            return float(val)
        except (ValueError, TypeError):
            return None

    player_id_set = {int(p) for p in player_ids}
    accum: dict[int, dict[str, list[tuple[float, float]]]] = {}
    for row in rows:
        pid_raw = row.get("player_id")
        if pid_raw is None:
            continue
        try:
            pid = int(pid_raw)
        except (ValueError, TypeError):
            continue
        if pid not in player_id_set:
            continue

        bucket = _PITCH_BUCKETS_K.get(row.get("pitch_type"))
        if bucket is None:
            continue
        whiff = _sf(row.get("whiff_percent"))
        pa = _sf(row.get("pa"))
        if whiff is None or not pa:
            continue
        accum.setdefault(pid, {}).setdefault(bucket, []).append((whiff, pa))

    result: dict[int, dict] = {}
    for pid, buckets in accum.items():
        splits = {}
        for key, bucket in (("whiff_fastball", "fastball"),
                             ("whiff_breaking", "breaking"),
                             ("whiff_offspeed", "offspeed")):
            samples = buckets.get(bucket)
            if not samples:
                splits[key] = None
                continue
            total_pa = sum(pa for _, pa in samples)
            splits[key] = sum(w * pa for w, pa in samples) / total_pa if total_pa else None
        if any(v is not None for v in splits.values()):
            result[pid] = splits
    return result


def _weighted_opp_whiff(pitcher_mix: dict, batter_splits: list[dict]) -> float | None:
    """
    Combine a pitcher's pitch-mix usage (fractions summing to ~1.0, keys
    "fastball"/"breaking"/"offspeed") with each confirmed opposing batter's
    whiff-by-bucket splits into one matchup scalar: for each batter, sum
    their bucket whiff% weighted by the pitcher's usage of that bucket,
    then average across the lineup. Returns None for an empty lineup.
    """
    if not batter_splits:
        return None
    per_batter = []
    for splits in batter_splits:
        total = 0.0
        for bucket_key, mix_key in (("whiff_fastball", "fastball"),
                                     ("whiff_breaking", "breaking"),
                                     ("whiff_offspeed", "offspeed")):
            val = splits.get(bucket_key)
            if val is None:
                continue
            total += val * pitcher_mix.get(mix_key, 0.0)
        per_batter.append(total)
    if not per_batter:
        return None
    return round(sum(per_batter) / len(per_batter), 2)


def _score_pitcher(sig: dict) -> float:
    """
    Score a starting pitcher 0-∞ for strikeout prop value. Higher = better
    K pick today. Deterministic — no LLM involved. Thresholds are seeded
    from published K-prop research (MLB average K% ~22-23%, whiff% ~24-25%,
    CSW% ~29%, SwStr% ~11%) and are meant to be tuned later via
    optimize_weights_k.py's correlation report once labeled data exists.
    """
    score = 0.0

    k_pct = sig.get("k_percent")
    if k_pct is not None:
        if k_pct >= 30: score += 4
        elif k_pct >= 27: score += 3
        elif k_pct >= 24: score += 2
        elif k_pct >= 21: score += 1
        elif k_pct < 18: score -= 1

    whiff = sig.get("whiff_percent")
    if whiff is not None:
        if whiff >= 32: score += 3
        elif whiff >= 28: score += 2
        elif whiff >= 25: score += 1
        elif whiff < 20: score -= 1

    csw = sig.get("csw_percent")
    if csw is not None:
        if csw >= 33: score += 2
        elif csw >= 30: score += 1
        elif csw < 26: score -= 1

    swstr = sig.get("swinging_strike_percent")
    if swstr is not None:
        if swstr >= 14: score += 2
        elif swstr >= 12: score += 1
        elif swstr < 9: score -= 1

    k9 = sig.get("k_per_9_blended")
    if k9 is not None:
        if k9 >= 11: score += 4
        elif k9 >= 9.5: score += 3
        elif k9 >= 8: score += 2
        elif k9 >= 6.5: score += 1
        elif k9 < 5: score -= 1

    for key in ("pitcher_whiff_fastball", "pitcher_whiff_breaking", "pitcher_whiff_offspeed"):
        val = sig.get(key)
        if val is None:
            continue
        if val >= 35: score += 1
        elif val < 20: score -= 0.5

    opp_whiff = sig.get("opp_whiff_vs_mix")
    if opp_whiff is not None:
        if opp_whiff >= 27: score += 3
        elif opp_whiff >= 24: score += 2
        elif opp_whiff >= 21: score += 1
        elif opp_whiff < 17: score -= 1

    avg_ip = sig.get("avg_ip_last3")
    if avg_ip is not None:
        if avg_ip >= 6.0: score += 2
        elif avg_ip >= 5.5: score += 1
        elif avg_ip < 4.5: score -= 2

    avg_pitches = sig.get("avg_pitches_last3")
    if avg_pitches is not None:
        if avg_pitches >= 95: score += 1
        elif avg_pitches < 80: score -= 1

    rest = sig.get("days_rest")
    if rest is not None:
        if rest <= 3: score -= 2
        elif rest == 4: score -= 1
        elif 5 <= rest <= 7: pass
        elif 8 <= rest <= 10: score += 0.5
        else: score -= 1  # >10 days — likely rust from an extended layoff

    ev = sig.get("ev_10")
    if ev is not None:
        if ev > 3: score += 5
        elif ev > 1: score += 3
        elif ev > 0: score += 1
        elif ev > -1: score -= 1
        else: score -= 3

    return score
